"""
PyNode - A Node-RED-like Visual Workflow System with Python Backend
"""

# Tune CPU thread pools before heavy libraries (torch/OpenMP) initialise, so
# the OMP_WAIT_POLICY change takes effect. See pynode._perf for rationale.
from pynode._perf import configure_inference_threads

configure_inference_threads()

from pynode.workflow_engine import WorkflowEngine


def _resolve_version() -> str:
    """Best-effort package version.

    Prefers the installed distribution metadata (the authoritative version for
    a `pip install`), then the file setuptools_scm writes at build time, and
    finally a placeholder for a bare source checkout that was never built.
    """
    try:
        from importlib.metadata import PackageNotFoundError, version
        try:
            return version("pynode-flow")
        except PackageNotFoundError:
            pass
    except Exception:
        pass
    try:
        from pynode._version import __version__ as _scm_version  # generated by setuptools_scm
        return _scm_version
    except Exception:
        return "0.0.0+unknown"


__version__ = _resolve_version()
__all__ = ['WorkflowEngine', '__version__']
